### ISSUE TITLE
SyntaxError: 'yield' inside async function

### ISSUE THREAD

**Issue by maynewong** [python-trio/trio-amqp#2]
```
Traceback (most recent call last):
  File "worker.py", line 2, in <module>
    import trio_amqp
  File "/usr/lib/python3.5/site-packages/trio_amqp/__init__.py", line 45
    yield amqp
           ^
```

**Comment by njsmith** [comment]
Using python 3.6 will fix that.

I'm not the trio-ampq maintainer, so I don't know if it's supposed to work on python 3.5 or not. But that's 3.6 syntax.

**Comment by maynewong** [comment]
@njsmith Thank you, it can run in python 3.6

**Comment by smurfix** [comment]
It's possible to do async iterators in 3.5, but the compatibility workaround is very annoying when you need to debug anything, so I didn't put it in yet. I'll fix that shortly.

**Comment by smurfix** [comment]
done by now, so closing.
