### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by mikenerone** [python-trio/trio-amqp#9]
I'd like to ask what the current status of the `trio-amqp` project is. Is this considered production ready and recommended for use? I notice it's a bit behind on merges from the `aioamqp` project from which it was forked, but not having dug into it, that may be because it is now independent, and any needs that apply have been addressed.

I also notice that you have an `anyio`-oriented AMQP implementation at https://github.com/M-o-a-T/asyncamqp, which is up to date with `aioamqp`, but has not been published to PyPI (in fact, there's now a separate project published under the same name). Is that the library you would recommend for use in a `trio` application currently?

Any related guidance you might be able to provide regarding a client library (for RabbitMQ specifically if that matters) in a trio-based app would be appreciated (even if these libraries aren't production-ready and the suggestion is to use an `asyncio` lib via `trio-asyncio` instead).

**Comment by smurfix** [comment]
The pypi asyncamqp was there earlier, I didn't yet rename the thing. I've been using trio-amqp in production for a couple months, seems to be stable enough, but what do I know ;-)

It's probably easiest to merge the MoaT asyncamqp back into trio-amqp and continue to use that name.

**Comment by mikenerone** [comment]
Thanks much for the update. I will go ahead and use `trio-amqp` then. :)
